name: MCBBS_Modpack_Period

# Controls when the action will run. 
on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * *"

  jobs:
    Run:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Run DateImage
          run: sudo java -jar ${GITHUB_WORKSPACE}/mcbbs_modpack_period.jar

        - name: Commit processor changes
          uses: EndBug/add-and-commit@v7
          with:
            message: "Update MCBBS Modpack Period Image"
